name: Build & deploy
on:
  workflow_dispatch:
jobs:
  build:
    if: github.ref_name == 'master' || github.ref_name == 'development'
    name: Build
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}
      url: https://${{ github.ref_name }}.env
    concurrency: ${{ github.workflow }}-${{ github.ref_name }}
    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Checkout code
        uses: actions/checkout@v2

      - run: echo ${{ github.ref_name }}.
        shell: bash