name: Build & deploy
on:
  workflow_dispatch:
jobs:
  build:
    if: github.ref_name == 'master' || github.ref_name == 'development'
    name: Build
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    concurrency: ${{ github.ref_name }}
    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Checkout code
        uses: actions/checkout@v2

      # https://github.com/marketplace/actions/setup-php-action
      - name: Setup PHP 8.1
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install dependencies
        shell: bash
        run: composer install --prefer-dist --no-dev

      # https://github.com/marketplace/actions/upload-a-build-artifact
      - name: Create artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact-release-without-tests
          path: |
            **
            !tests/**
            !.git/**

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}
      url: https://${{ github.ref_name }}.env
    concurrency: ${{ github.ref_name }}
    steps:
      # https://github.com/marketplace/actions/download-a-build-artifact
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: artifact-release-without-tests