name: Build & deploy
on:
  workflow_dispatch:
jobs:
  build:
    if: github.ref_name == 'master' || github.ref_name == 'development'
    name: Create build for ${{ github.ref_name }}
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    concurrency: ${{ github.ref_name }}
    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Checkout code
        uses: actions/checkout@v2

      # https://github.com/marketplace/actions/setup-php-action
      - name: Setup PHP 8.1
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install dependencies
        shell: bash
        run: composer install --prefer-dist --no-dev

      # https://github.com/marketplace/actions/upload-a-build-artifact
      - name: Create artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact-release-without-tests
          path: |
            **
            !tests/**
            !.git/**

  deploy:
    name: Deploy to ${{ github.ref_name }}
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}
      url: https://${{ github.ref_name }}.env
    concurrency: ${{ github.ref_name }}
    steps:
      # https://github.com/marketplace/actions/download-a-build-artifact
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: artifact-release-without-tests

      # https://github.com/marketplace/actions/rsync-deployments-action
      - name: Rsync build to server
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -avzr --delete
          path: .
          remote_path: /var/www/app/
          remote_host: ${{ github.ref_name }}.env
          remote_user: ${{ secrets.USERNAME }}
          remote_key: ${{ secrets.KEY }}

      # https://github.com/marketplace/actions/ssh-remote-commands
      - name: Run remote SSH commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/app/
            # Put in maintenance mode
            # Run database migrations
            # Clear cache
            # Disable mainenance mode