name: CI/CD
on:
  push: # @TODO: REMOVE AFTER TESTING
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  test-suite:
    name: Test suite
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP 8.1 with Xdebug 3.x
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: xdebug

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: composer install --prefer-dist

      - name: Run test suite
        run: vendor/bin/phpunit --testsuite unit --coverage-clover clover.xml

      - name: Check minimum required code coverage
        run: |
          CODE_COVERAGE=$(vendor/bin/coverage-checker clover.xml 90 --processor=clover-coverage)
          echo ${CODE_COVERAGE}
          if [[ ${CODE_COVERAGE} == *"give yourself a"* ]] ; then
            exit 1;
          fi

      - name: Send test coverage to codecov.io
        uses: codecov/codecov-action@v2.1.0
        with:
          files: clover.xml
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)


  php-stan-php-cs:
    name: PHPstan (level 9) & PHPcs
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP 8.1
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: composer install --prefer-dist

      - name: Run PHPstan
        run: vendor/bin/phpstan analyse

      - name: Run PHPcs fixer dry-run
        run: vendor/bin/php-cs-fixer fix --dry-run --stop-on-violation --using-cache=no --config=.php-cs-fixer.dist.php