name: CI/CD
on:
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/setup-php-action
      - name: Setup PHP 8.1
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      # https://github.com/marketplace/actions/checkout
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: composer install --prefer-dist

      # https://github.com/marketplace/actions/upload-a-build-artifact
      - name: Create artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact-release-without-tests
          path: |
            **
            !tests/**